In [ ]:
!pip install yfinance

In [ ]:
import yfinance as yf
import pandas as pd
import numpy as np
#setup
#code
ticker = yf.Ticker('GOOG') #import data
aapl_df = ticker.history(period="5y") #get data from 5 year period in dataframe
aapl_df.drop(['High','Close','Volume','Dividends','Stock Splits'], axis=1, inplace=True) #only have two columns, not seven, apple df is dataframe
open = np.empty(shape = (1259), dtype = float) #open and close are data lists
close = np.empty(shape = (1259), dtype = float)

open=aapl_df[['Open']].to_numpy() #list of only open price
print(open)

[[ 66.73811051]
 [ 66.91067304]
 [ 67.37653779]
 ...
 [172.77999878]
 [177.32000732]
 [173.88000488]]


In [ ]:
open=aapl_df[['Open']].to_numpy()
max = 0

for i in range(1258):
  if open[i] > max:
    max = open[i]
print(max)

[191.49791157]


In [ ]:
open=aapl_df[['Open']].to_numpy()
min = 9999999999

for i in range(1258):
  if open[i] < min:
    min = open[i]
print(min)

[52.69608589]


In [ ]:
open=aapl_df[['Open']].to_numpy()
max = 0

for i in range(1258):
  if open[i] > max and open[i] < 100:
    max = open[i]
print(max)



[99.81486676]


In [ ]:
open_set = {5, 8, 9, 7, 3, 10}
max_value = 0
second_max_value = 0

for i in open_set:
    if i > max_value:
        second_max_value = max_value  # Update second max before max
        max_value = i  # Update max
    elif i > second_max_value:
        second_max_value = i  # Update second max if i is less than max but greater than second_max

print("Max:", max_value)
print("Second Max:", second_max_value)

Max: 10
Second Max: 9


In [ ]:
open=aapl_df[['Open']].to_numpy()
counter = 0
for i in range(1258):
  if open[i] > 100 and open[i] < 110:
    counter = counter + 1
print(counter)


125


In [ ]:
X = np.zeros((1260,3)) #defines x varible. list of 1260 lines with two columns
y = [0]*1260 #list of one dimension which has 1260 lines
print(X[0])
print(y[0])
for i in range(1250):
  X[i] =  [open[i][0],open[i+1][0],open[i+2][0]] #first 2 open values
  y[i] =  open[i+3][0] #open value after the first 2
print(X[0])
print(y[0])

[0. 0. 0.]
0
[66.73811051 66.91067304 67.37653779]
67.13213742113231


In [ ]:
from sklearn.model_selection import train_test_split
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33) #x train and x test are subsets of x
linear = linear_model.LinearRegression() #when linear is used it is using the linear regression model
linear.fit(X_train, y_train) #finding the weights (w1, w2) that work well for the training data
y_pred_linear = linear.predict(X_test) #based off of the weights it predicts the y value
y_pred_linear_train = linear.predict(X_train)
print("Mean squared error: %.2f" % mean_squared_error(y_test, y_pred_linear)) #mean squared error is the difference between the actual price and predicted price squared, and then find the average of all of this
print("Mean squared error: %.2f" % mean_squared_error(y_train, y_pred_linear_train))
print("Coefficients: \n", linear.coef_) #(w1 and w2)

error_linear = mean_squared_error(y_test, y_pred_linear)

#y = p1w1 + p2w2
print(y_pred_linear[10])
print(y_test[10])

Mean squared error: 6.60
Mean squared error: 4.57
Coefficients: 
 [0.02063225 0.06859077 0.91053456]
148.93501057281406
150.6300784743541


In [ ]:
from sklearn.neural_network import MLPRegressor

neural = MLPRegressor(random_state=1, max_iter=500).fit(X_train, y_train) #defines neural model and finds the weights
y_pred_neural = neural.predict(X_test) #from the weights before it is predicting the y value
y_pred_neural_train = neural.predict(X_train)
print("Mean squared error: %.2f" % mean_squared_error(y_test, y_pred_neural))
print("Mean squared error: %.2f" % mean_squared_error(y_train, y_pred_neural_train))
print(y_pred_neural[10])
print(y_test[10])
error_neural = mean_squared_error(y_test, y_pred_neural)



Mean squared error: 7.30
Mean squared error: 4.95
149.34028655037682
150.6300784743541


In [ ]:
from sklearn.tree import DecisionTreeRegressor
tree = DecisionTreeRegressor(max_depth=8) #max_depth is max number of branches you can have
tree.fit(X_train, y_train) #builds the tree
y_pred_tree = tree.predict(X_test)
y_pred_tree_train = tree.predict(X_train)
print("Mean squared error: %.2f" % mean_squared_error(y_test,y_pred_tree))
print("Mean squared error: %.2f" % mean_squared_error(y_train,y_pred_tree_train))
print(y_pred_tree[400])
error_tree = mean_squared_error(y_test, y_pred_tree)


Mean squared error: 9.39
Mean squared error: 1.67
123.82249637727818


In [ ]:
from sklearn.ensemble import RandomForestRegressor
forest = RandomForestRegressor(max_depth=5, random_state=0)
forest.fit(X_train, y_train)
y_pred_forest = forest.predict(X_test)
y_pred_forest_train = forest.predict(X_train)
print("Mean squared error: %.2f" % mean_squared_error(y_test,y_pred_forest))
print("Mean squared error: %.2f" % mean_squared_error(y_train,y_pred_forest_train))
print(y_pred_forest[2])
error_forest = mean_squared_error(y_test, y_pred_forest)



Mean squared error: 8.21
Mean squared error: 3.68
137.04255411238861


In [ ]:
Amount = 100000
Stocks = 0
predictions = linear.predict(X)
for i in range(1250):
  if predictions[i+1] > y[i] and Amount > y[i]:
    Stocks = Stocks + 1
    Amount = Amount - y[i]
  elif predictions[i+1] < y[i] and Stocks > 0:
    Stocks = Stocks - 1
    Amount = Amount + y[i]
  if (i ==1249):
    Amount = Stocks * y[i] + Amount
    Stocks = 0
print(Amount)
#

144620.11239250694


In [ ]:
Amount = 1000
Stocks = 0
predictions = linear.predict(X)
for i in range(1250):
  if predictions[i+1] > y[i] and Amount > y[i] * 2:
    Stocks = Stocks + 2
    Amount = Amount - y[i] * 2
  elif predictions[i+1] < y[i] and Stocks > 1:
    Stocks = Stocks - 2
    Amount = Amount + y[i] * 2
  if (i ==1249):
    Amount = Stocks * y[i] + Amount
    Stocks = 0
print(Amount)
#

2424.7955998784287


In [ ]:
Average = 0.25 * (y_pred_linear + y_pred_neural + y_pred_forest + y_pred_tree)
print("Mean squared error: %.2f" % mean_squared_error(Average, y_test))

Average_2 = 0.5 * (y_pred_linear + y_pred_neural)
print("Mean squared error: %.2f" % mean_squared_error(Average_2, y_test))

weight_linear = 1/error_linear
weight_neural = 1/error_neural
weight_forest = 1/error_forest
weight_tree = 1/error_tree
sum = weight_linear + weight_neural + weight_forest + weight_tree
weight_linear = weight_linear/sum
weight_neural = weight_neural/sum
weight_forest = weight_forest/sum
weight_tree = weight_tree/sum
weighted_Average = weight_linear * y_pred_linear + weight_neural * y_pred_neural + weight_forest * y_pred_forest + weight_tree * y_pred_tree
print("Mean squared error: %.2f" % mean_squared_error(weighted_Average, y_test))

Mean squared error: 7.02
Mean squared error: 6.86
Mean squared error: 6.95
